### ISSUE TITLE
API Controller

### ISSUE THREAD

**Issue by lav45** [hiqdev/yii2-hiart#1]
Можете добавить пример RestAPI контроллера с которым происходит взаимодействие.

Было бы неплохо описать примеры вызав каких http запросов будут приведены к каким SQL запросам на старане ResrAPI сервера.

**Comment by hiqsol** [comment]
Дело в том что наше АПИ с которым мы работаем написано не на yii и это внутренняя разработка код показать не можем. И оно не совсем REST, экшены различаются не по HTTP-методу, а по урлу, например запросы идут такие:

```
https://api.domain.com/clientsSearch?access_token=6d9125f2fccf00f70f196c9307725d2b79959f0f
```

и остальные параметры постом.

В данный момент эта либа хоть уже и многое умеет, но всё таки **на начальной стадии разработки** и пока работает только именно с нашим апи.  Мы вообще-то планируем дорабатывать чтобы можно было работать с разными апи, в том числе yii2\rest\ActiveController. Но это будет через пару месяцев, врядли раньше.

**Comment by hiqsol** [comment]
Переделали либу сверху донизу, теперь может работать с любым API.
Есть базовая реализация REST'а, зы README.
Также в качестве примера реализовали GitHub API [yii2-hiart-github](https://github.com/hiqdev/yii2-hiart-github).
Своё конкретное АПИ несложно реализовать: отнаследоваться от REST'а и переопределить пару методов.
