### ISSUE TITLE
parse_url() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by camoralb** [hiqdev/yii2-hiart#14]
Hi, I am implementing in Yii2 but it gives me this error although I have changed the guzzle and yii-httpclient transport. I can't understand. When I debug, I see $this->uri in Response.php and it is an array with the models name.

![captura de pantalla de 2018-03-28 20-09-50](https://user-images.githubusercontent.com/15915665/38066276-7c4bedf0-32c4-11e8-9c31-e12331edb4b0.png)

**Comment by hiqsol** [comment]
Please give more information.

`$this->url` should be url to your API like https://your-api.com/command
What exactly does it hold instead?

Also could you please show application config part concerning yii2-hiart.
It should be something like:

```php
'components' => [
    'hiart' => [
        'class' => ....,
        ...,
    ],
```

**Comment by hiqsol** [comment]
Closing as too old.
