### ISSUE TITLE
Authentication tools

### ISSUE THREAD

**Issue by vedro-compota** [hiqdev/yii2-hiart#17]
Hi there)
What about authentication in `hiqdev/yii2-hiart`? Is there any ability to set auth token to auth at API server?
Also is there ability to add GET-param (for auth) for all API requests?

**Comment by SilverFire** [comment]
Hello. There is an abstract method `getAuth()` in AbstractQueryBuilder: 

https://github.com/hiqdev/yii2-hiart/blob/master/src/AbstractQueryBuilder.php#L68

Implement it to add your authentication data to the request.




> Also is there ability to add GET-param (for auth) for all API requests?

Yes, check out implementation example in https://github.com/hiqdev/hipanel-hiart/tree/master/src

**Comment by vedro-compota** [comment]
> There is an abstract method getAuth() in AbstractQueryBuilde

@SilverFire thanks!

> Yes, check out implementation example in https://github.com/hiqdev/hipanel-hiart/tree/master/src

Where's example here  https://github.com/hiqdev/hipanel-hiart/tree/master/src ? I can't find.

**Comment by hiqsol** [comment]
`getAuth()` is in Connection:

https://github.com/hiqdev/hipanel-hiart/blob/master/src/Connection.php#L126

**Comment by vedro-compota** [comment]
@hiqsol thank you)
