### ISSUE TITLE
Set the API action for find()

### ISSUE THREAD

**Issue by InAdavansP** [hiqdev/yii2-hiart#18]
Hi,

How can i set the api action for the fin() method? 
Actually this is only `BaseUrl/ModelName?params.`

But my API action is view : `BaseUrl/ModelName/view?params.`

**Comment by hiqsol** [comment]
This is how we use hiart most - for `find`.
You need to create your QeryBuilder and customize buildUri and possibly other methods for your API.

Please see https://github.com/hiqdev/hipanel-hiart/blob/master/src/QueryBuilder.php
We've created query builder for our old and rather non standard rest API.

**Comment by InAdavansP** [comment]
Thank you, it was exactly the link i needed.
