### ISSUE TITLE
/src/Connection.php#L426-L433 unreachable

### ISSUE THREAD

**Issue by bscheshirwork** [hiqdev/yii2-hiart#4]
[/src/Connection.php#L426-L433](https://github.com/hiqdev/yii2-hiart/blob/3b7614f4581c7ef6cc0ae3e68f525896c0a5c6ea/src/Connection.php#L426-L433) unreachable

**Comment by SilverFire** [comment]
This method is ugly and will be dropped soon because we've already implemented Guzzle.
Thank you
