### ISSUE TITLE
Unknown component ID: hiresource

### ISSUE THREAD

**Issue by izemize** [hiqdev/yii2-hiart#6]
I have installed 0.0.1 version, and after following readme, i get Unknown component ID: hiresource error. What am I missing?
I don't have / need mysql db connection, because i try search with remote api called.
Thanks

**Comment by andygphillips** [comment]
I'm just setting this up today as well, and I needed this in my config (different from the readme):

```
    'hiresource' => [
        'class' => 'hiqdev\hiart\Connection',
        'config' => [
            'api_url' => 'https://myapi.com/',
        ],
    ],
```

**Comment by SilverFire** [comment]
Yepp, @phillipsdesign is right. The extension was called `hiresource` and we are renaming it to `hiart`.
I'll bump a release with removed `hiresource` mentions soon. Thank you

**Comment by SilverFire** [comment]
I've issued a release https://github.com/hiqdev/yii2-hiart/releases/tag/0.0.2

**Comment by izemize** [comment]
Thanks. How can i send request and process response Flick Api getRencent with this stuff?

https://www.flickr.com/services/api/explore/flickr.photos.getRecent (click to call method) i'm get Client error: `SETUSERAGENT https://api.flickr.com/hiart/0.x` resulted in a `404 Not Found` response:

**Comment by SilverFire** [comment]
@izemize please create a separate issue and show some code you're trying to use among with the configs
