### ISSUE TITLE
Improve Command to return the Response class

### ISSUE THREAD

**Issue by edgardmessias** [hiqdev/yii2-hiart#8]
Several APIs use header for some extra data.

Refactor Query and ActiveQuery to handle Response.

Example: https://libraries.io/api/ - Exists in header the total results

**Comment by edgardmessias** [comment]
Example:

```php
    public function search($db = null) {
        return $this->createCommand($db)->search()->getData();
    }    
    
    public function count($q = '*', $db = null) {
        $this->count = $q;

        /* @var $response \hiqdev\hiart\ResponseInterface */
        $response = $this->createCommand($db)->search();
        
        $header = $response->getHeader('total');
        
        if(!empty($header)){
            return (int) $header[0];
        }
        
        return 0;
    }

```

**Comment by hiqsol** [comment]
This is what I'm looking at right now.

**Comment by edgardmessias** [comment]
My suggestion:

`QueryBuilder` return a `Request` class.
`Query` return a `Response` class.
`Request` class has a attribute with a parser callable, example: A method `getParsedResponse` execute the parser in `Request` class and return part of reader.
`Response` class contains the `Request` class, to read the parser, example: A method `getParsedResponse` execute the parser in `Request` class and return part of reader.

The `QueryBuilder` set the parser.

**Comment by hiqsol** [comment]
Sorry for the long delay.

`Command::send()` returns Response object now.

So I think the issue is resolved now.
Please create a new issue if you have more ideas.
